tp_escolas/Controllers/PaisController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;
using tp_escolas.Models;
using tp_escolas.Models.ViewModels;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq.Expressions;
using System.Data.Entity;

namespace tp_escolas.Controllers
{
    [Authorize(Roles = RolesConst.Pai)]
    public class PaisController : Controller
    {

        private EscolaContext _db;
        private ApplicationDbContext _UserDb;
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;


        public PaisController()
        {
            _db = new EscolaContext();
            _UserDb = new ApplicationDbContext();

        }
        public PaisController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Pais
        public ActionResult Index()
        {
            var uId = User.Identity.GetUserId();
            ViewBag.Id = _db.Pais.Where(u => u.UserID == uId).Select(u => u.PaisID).FirstOrDefault();
            return View();
        }

        //Get: Pais/Registo
        [AllowAnonymous]
        public ActionResult Registo()
        {
            if (User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");
            ViewBag.CidadeID = new SelectList(_db.Cidades, "CidadeID", "CidadeNome");
            return View();
        }

        // GET: Pais/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }



        // POST: Pais/Create
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> Registo(PaiViewModelAdd pai)
        {
            try
            {

                ViewBag.CidadeID = new SelectList(_db.Cidades, "CidadeID", "CidadeNome");


                if (_UserDb.Users.Any(y => y.Email == pai.Email))
                {
                    ModelState.AddModelError("Email", "Conta já existente!");

                    return View();
                }
                if (pai.Cidade.CidadeID.ToString() == "")
                {
                    return View();
                }

                if (ModelState.IsValid)
                {

                    var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(_UserDb));
                    var user = new ApplicationUser { UserName = pai.Email, Email = pai.Email };
                    var result = await UserManager.CreateAsync(user, pai.Password);

                    if (result.Succeeded)
                    {

                        if (!roleManager.RoleExists(RolesConst.Pai))
                        {
                            var role = new IdentityRole();
                            role.Name = RolesConst.Pai;
                            roleManager.Create(role);
                        }

                        result = UserManager.AddToRole(user.Id, RolesConst.Pai);

                        if (result.Succeeded)
                        {
                            try
                            {
                                Pai p = new Pai();

                                p.Cidade = _db.Cidades.FirstOrDefault(c => c.CidadeID == pai.Cidade.CidadeID);
                                p.UserID = user.Id;
                                p.Nome = pai.Nome;
                                p.Morada = pai.Morada;
                                p.CodPostal = pai.CodPostal;
                                p.Telefone = pai.Telefone;

                                _db.Pais.Add(p);
                                _db.SaveChanges();

                                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                                return RedirectToAction("Index");
                            }
                            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
                            {
                                //RollBack 
                                UserManager.RemoveFromRole(user.Id, RolesConst.Pai);
                                result = UserManager.Delete(user);
                                foreach (var validationErrors in dbEx.EntityValidationErrors)
                                {
                                    foreach (var validationError in validationErrors.ValidationErrors)
                                    {
                                        ModelState.AddModelError("", "\n" + string.Format("{0}:{1}",
                                            validationErrors.Entry.Entity.ToString(),
                                            validationError.ErrorMessage));

                                        // raise a new exception nesting
                                        // the current instance as InnerException

                                    }
                                }
                                return View();
                            }

                        }
                        else
                            UserManager.Delete(user); //RollBack Role
                    }
                    else
                        AddErrors(result);
                }

                return View();

            }
            catch
            {
                return View();
            }
        }

        // GET: Pais/Edit/5
        public ActionResult Edit( )
        {
            var UserId = User.Identity.GetUserId();
            var id = _db.Pais.Where(w => w.UserID == UserId).Select(s => s.PaisID).FirstOrDefault();

            Pai p = new Pai();
            p = _db.Pais.FirstOrDefault(fs => fs.PaisID == id);

            PaiViewModelEdit pai = new PaiViewModelEdit();
            pai.Morada = p.Morada;
            pai.CodPostal = p.CodPostal;
            pai.Telefone = p.Telefone;
            pai.Nome = p.Nome;
            pai.Cidade = p.Cidade;
            pai.Cidades = _db.Cidades.ToList();

            return View(pai);
        }

        // POST: Pais/Edit/5
        [HttpPost]
        public ActionResult Edit(PaiViewModelEdit pai)
        {
            try
            {
                pai.Cidades = _db.Cidades.ToList();
                if (ModelState.IsValid)
                {
                    var Uid = User.Identity.GetUserId();

                    var p = _db.Pais.FirstOrDefault(fs => fs.UserID == Uid);

                    p.Morada = pai.Morada;
                    p.Nome = pai.Nome;
                    p.Telefone = pai.Telefone;
                    p.CodPostal = pai.CodPostal;
                    p.Cidade = _db.Cidades.FirstOrDefault(c => c.CidadeID == pai.Cidade.CidadeID);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(pai);
                // TODO: Add update logic here


            }
            catch
            {
                return View(pai);
            }
        }

        // GET: Pais/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Pais/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        public ActionResult Avaliacao()
        {
            var UserId = User.Identity.GetUserId();
            var id = _db.Pais.Where(w => w.UserID == UserId).Select(s => s.PaisID).FirstOrDefault();
            ListaInst(Convert.ToInt32(id));
            return View();
        }
        [HttpPost]
        public ActionResult Avaliacao(AvaliacaoViewModelAdd av)
        {
            var Uid = User.Identity.GetUserId();
            var id = _db.Pais.Where(w => w.UserID == Uid).Select(s => s.PaisID).Single();
            ListaInst(Convert.ToInt32(id));
            try
            {
                if (ModelState.IsValid)
                { 
                    Avaliacao a = new Avaliacao();
                    a.Pais = _db.Pais.Find(Convert.ToInt32(id));
                    a.Data = DateTime.Now;
                    a.Instituicoes = _db.Instituicoes.Find(av.InstituicoesID);
                    a.Nota = av.Nota;
                    a.Descricao = av.Descricao;
                    _db.Avaliacoes.Add(a);
                    _db.SaveChanges();
                    return RedirectToAction("Index"); 

                }

                return View();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                //RollBack 
                foreach (var validationErrors in dbEx.EntityValidationErrors)

tp_escolas/Views/Shared/_Layout.cshtml
@using tp_escolas.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar navbar-expand-lg navbar-dark bg-primary" style="    width: inherit;">
                <button type="button" class="navbar-toggle btn btn-warning" data-toggle="collapse" data-target=".navbar-collapse" style="margin: .3em;">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Space4Children", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Lista Instituições", "ListaInstituicoes", "Instituicao", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("About us", "About", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.Partial("_LoginPartial")
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="position: absolute;z-index:1000">
                    @if (User.Identity.IsAuthenticated && User.IsInRole(RolesConst.Admin))
                    {
                        <li style="margin-top:2px;">@Html.ActionLink("Admin Home", "Index", "Admin", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Aceitar Instituição", "Aceitar", "Admin", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Gestão Servicos", "ServicoDelEdit","Admin", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Gestão Tipo Ensino", "TipoEnsinoDelEdit", null, "Admin", new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Gestão Pais", "PaisEditDel", "Admin", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Gestão Instituições", "InstituicaoEditDel", null, "Admin", new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Gestão Admins", "AdminAddDel", "Admin", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Gestão De Cidades", "CidadesAddEdit", "Admin", null, new { @class = "btn btn-warning" })</li>
                    }@if (User.Identity.IsAuthenticated && User.IsInRole(RolesConst.Pai))
                    {
                        <li style="margin-top:2px;">@Html.ActionLink("Pais Home", "Index", "Pais", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Avaliação", "Avaliacao", "Pais", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Historico Avaliações", "HistAvaliacoes", "Pais", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Lista Actividades das escolas", "LstActividades", null, "Pais", new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Pedir Informações", "LstIns", "Pais", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Editar Dados", "Edit", "Pais", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Pesquisa Avançada", "Pesquisa", "Pais", null, new { @class = "btn btn-warning" })</li>

                    }@if (User.Identity.IsAuthenticated && User.IsInRole(RolesConst.Instituicao))
                    {
                        <li style="margin-top:2px;">@Html.ActionLink("Instituicao Home", "Index", "Instituicao", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Adicionar / Editar Serviços Especificos", "ServicosLista", "Instituicao", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Aceitar Pais", "ListaPais", "Instituicao", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Gestão de Actividades", "ListaAct", "Instituicao", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Vizualizar Avaliação", "Avaliacoes", "Instituicao", null, new { @class = "btn btn-warning" })</li>
                        <li style="margin-top:2px;">@Html.ActionLink("Ver Informação", "Info", "Instituicao", null, new { @class = "btn btn-warning" })</li>


                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Space4Children ISEC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>