tp_escolas/Models/Avaliacao.cs
using System;
using System.Collections.Generic; 
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace tp_escolas.Models
{
    [Table("Avaliacoes")]
    public class Avaliacao
    { 
       
        [Key, Column(Order = 1), ForeignKey("Pais")]
        public int PaisID { get; set; }
        [Key, Column(Order = 2), ForeignKey("Instituicoes")] 
        public int InstituicoesID { get; set; }
        
        [Required]
        virtual public Pai Pais { get; set; }
        [Required]
        virtual public Instituicao Instituicoes { get; set; }

        public string Descricao { get; set; }
        [Range(1,10, ErrorMessage = "Por favor classifique entre 1 e 10")]
        public int Nota { get; set; }
        [ScaffoldColumn(false)]
        [Key,Column(Order =3)]
        public DateTime Data { get; set; }
    }
}

tp_escolas/Models/Pai.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.ComponentModel.DataAnnotations;
using System.Web.UI.WebControls;
using System.ComponentModel.DataAnnotations.Schema;
 using tp_escolas.ValidationAttributes;

namespace tp_escolas.Models
{

     

  [Table("Pais")]
    public class Pai
    {
        [Key]
        [ScaffoldColumn(false)]
        public int PaisID { get; set; }

        [Required]
        [MinPalavras(2, ErrorMessage = "{0} Demasiado pequeno")]  
        [Display(Name = "Nome Completo")]
        public String Nome { get; set; }

        [Required]
        [RegularExpression(@"^[0-9]{9}$")]
        [Display(Name = "Numero De Telefone")] 
        public int Telefone { get; set; }

        [Required]
        [StringLength(300, MinimumLength = 10)]
        public string Morada { get; set; }

        [Required] 
        virtual public Cidade Cidade { get; set; }

        [Required]
        [Display(Name = "Codigo Postal")]
        [RegularExpression(@"\d{4}(-\d{3})?$" , ErrorMessage = "Codigo Postal inválido")]
        public string CodPostal { get; set; }

        [ScaffoldColumn(false)]
        public string UserID {get;set;}
          
        virtual public IList<Avaliacao> Avaliacoes { get; set; }
        virtual public IList<PaiInstituicao> PaiInstituição { get; set; }
        
    }
}

tp_escolas/Controllers/InstituicaoController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;
using tp_escolas.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using tp_escolas.Models.ViewModels;
using System.Globalization;
using System.Data.Entity;

namespace tp_escolas.Controllers
{
    [Authorize(Roles = RolesConst.Instituicao)]
    public class InstituicaoController : Controller
    {
        private EscolaContext _db;
        private ApplicationDbContext _UserDb;
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;


        public InstituicaoController()
        {
            _db = new EscolaContext();
            _UserDb = new ApplicationDbContext();

        }
        public InstituicaoController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Instituicao

        public ActionResult Index()
        {
            var uId = User.Identity.GetUserId();
            ViewBag.Id = _db.Instituicoes.Where(u => u.UserID == uId).Select(u => u.InstituicaoID).FirstOrDefault();
            return View();
        }

        [AllowAnonymous]
        public ActionResult Registo()
        {
            if (User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");

            ViewBag.CidadeID = new SelectList(_db.Cidades, "CidadeID", "CidadeNome");

            InstituicaoViewModelAdd i = new InstituicaoViewModelAdd
            {
                Servicos = _db.Servicos.ToList(), 
                TiposEnsino = _db.TipoEnsino.ToList()
            };

            return View(i);
        }

        // GET: Instituicao/Details/5
        public ActionResult Details(int id)
        {

            return View();
        }

        [AllowAnonymous]
        public ActionResult Info(int? id)
        {
            if (id == null || id == 0) {
                var userId = User.Identity.GetUserId();
                var aux = _db.Instituicoes.FirstOrDefault(fs => fs.UserID == userId);
                if(aux != null)
                {
                    id = aux.InstituicaoID;
                }else
                return RedirectToAction("ListaInstituicoes");
            }
            InstituicaoViewModel inst = new InstituicaoViewModel();
            var i = _db.Instituicoes.Where(x => x.InstituicaoID == id).FirstOrDefault();

            inst.Cidade = i.Cidade;
            inst.CodPostal = i.CodPostal;
            inst.Morada = i.Morada;
            inst.Nome = i.Nome;
            inst.Telefone = i.Telefone;
            inst.TipoInstituicao = i.TipoInstituicao;

            inst.InstituicoesTipoEnsino = _db.InstituicaoTipoEnsino.Where(w => w.Instituicoes.InstituicaoID == id).ToList();
            //inst.TiposEnsino = _db.TipoEnsino.Where(w => w.InstituicoesTipoEnsino.Any(s => s.TipoEnsinoID == w.TipoEnsinoID && s.InstituicoesID == id)).ToList();
            inst.Servicos = _db.Servicos.Where(w => w.InstituicoesServicos.Any(s => s.ServicosID == w.ServicosID && s.InstituicoesID == id) ).ToList();

            

            inst.Ites = _db.InstituicoesTipoEnsinoServicos.Where(w => w.InstituicoesID == id).ToList();

            var serv = _db.Servicos.ToList(); 
             
            foreach (var it in serv)
            {
                 inst.Ites.Where(w => w.ServicosID == it.ServicosID)
                    .Select(s => { s.Servicos = it; return s; }).ToList();
            }

            return View(inst);
        }

        [AllowAnonymous]
        public ActionResult ListaInstituicoes( )
        {

            ViewBag.Cidades = ViewBag.CidadeID = new SelectList(_db.Cidades, "CidadeID", "CidadeNome");
            var inst = _db.Instituicoes.Where(w => w.Activa).ToList();
            foreach(var it in inst)
            {
               foreach(var item in it.Avaliacoes)
                {
                    it.NotaAvg += item.Nota;
                }
                it.NotaAvg = it.NotaAvg / it.Avaliacoes.Count;
            }
            return View(inst);
        }

        [AllowAnonymous]
        [HttpPost]
        public PartialViewResult ListaInstituicoes(int? id)
        {
            var inst = _db.Instituicoes.Where(w => w.Activa).ToList();
            if (id > 0)
                inst = inst.Where(w => w.Cidade.CidadeID == id).ToList();
            foreach (var it in inst)
            {
                foreach (var item in it.Avaliacoes)
                {
                    it.NotaAvg += item.Nota;
                }
                it.NotaAvg = it.NotaAvg / it.Avaliacoes.Count;
            }
            return PartialView("_ListaInstPartial", inst);
        }

        // POST: Instituicao/Registo
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> Registo(InstituicaoViewModelAdd inst)
        {
            try
            {
                ViewBag.CidadeID = new SelectList(_db.Cidades, "CidadeID", "CidadeNome");

                if (_UserDb.Users.Any(y => y.Email == inst.Email))
                {
                    ModelState.AddModelError("Email", "Conta já existente!");

                }
                if (inst.Cidade.CidadeID.ToString() == "")
                {
                    ModelState.AddModelError("Cidade", "Selecione uma Cidade Valida!");

                }
                if (inst.TipoInstituicao == 0)
                {
                    ModelState.AddModelError("TipoInstituicao", "Selecione uma Instituição!");

                }
                int count = 0;
                foreach (var it in inst.TiposEnsino)
                    if (it.IsSelected)
                        count++;
                if (count == 0)
                {
                    ModelState.AddModelError("TiposEnsino", "Selecione Pelo menos 1 Serviço de ensino!");

                }

                if (ModelState.IsValid)
                {
                    var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(_UserDb));
                    var user = new ApplicationUser { UserName = inst.Email, Email = inst.Email };
                    var result = await UserManager.CreateAsync(user, inst.Password);

                    if (result.Succeeded)
                    {

                        if (!roleManager.RoleExists(RolesConst.Instituicao))
                        {
                            var role = new IdentityRole();
                            role.Name = RolesConst.Instituicao;
                            roleManager.Create(role);
                        }

                        result = UserManager.AddToRole(user.Id, RolesConst.Instituicao);

                        if (result.Succeeded)
                        {
                            try
                            {
                                Instituicao i = new Instituicao();

                                i.UserID = user.Id;
                                i.Cidade = _db.Cidades.FirstOrDefault(c => c.CidadeID == inst.Cidade.CidadeID);
                                i.Morada = inst.Morada;
                                i.Nome = inst.Nome;
                                i.CodPostal = inst.CodPostal;
                                i.Telefone = inst.Telefone;
                                i.TipoInstituicao = inst.TipoInstituicao;

                                _db.Instituicoes.Add(i);
                                _db.SaveChanges();


                                foreach (var it in inst.Servicos)
                                {
                                    if (it.IsSelected)
                                    {
                                        var instSer = new InstituicaoServico();
                                        instSer.InstituicoesID = i.InstituicaoID;
                                        instSer.ServicosID = it.ServicosID;
                                        _db.InstituicoesServicos.Add(instSer);
                                    }

                                }

                                foreach (var it in inst.TiposEnsino)
                                {
                                    if (it.IsSelected)
                                    {
                                        var instTEnsi = new InstituicaoTipoEnsino();
                                        instTEnsi.InstituicoesID = i.InstituicaoID;
                                        instTEnsi.TipoEnsinoID = it.TipoEnsinoID;
                                        instTEnsi.Valor = it.Valor;
                                        _db.InstituicaoTipoEnsino.Add(instTEnsi);
                                    }
                                }

                                _db.SaveChanges();
                                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                                return RedirectToAction("Index");
                            }
                            catch (Exception e)
                            {

tp_escolas/Views/Pais/Avaliacao.cshtml
@model tp_escolas.Models.ViewModels.AvaliacaoViewModelAdd

@{
    ViewBag.Title = "Avaliacao";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Avaliacao</h2>
@if (ViewBag.Inst == null)
{
    @Html.Label("Não Ha escolas disponiveis para avaliar!")
}
else
{
     using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Avaliacao</h4>
            <hr />
            <div class="form-group">
                @Html.Label("Escolha a Institução", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.InstituicoesID, ViewBag.Inst as IEnumerable<SelectListItem>)

                </div>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Nota, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nota, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nota, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

tp_escolas/Views/Pais/Edit.cshtml
@model tp_escolas.Models.ViewModels.PaiViewModelEdit

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Alterar os Dados</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
         
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Morada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Morada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Morada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodPostal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodPostal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodPostal, "", new { @class = "text-danger" })
            </div>
        </div>
         
        <div class="form-group">
            @Html.LabelFor(model => model.Cidade, "Cidade", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Cidade.CidadeID, new SelectList(Model.Cidades, "cidadeID", "cidadeNome"))
                @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

tp_escolas/Views/Pais/HistAvaliacoes.cshtml
@model IEnumerable<tp_escolas.Models.Avaliacao>

@{
    ViewBag.Title = "HistAvaliacoes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Historico De Avaliaçôes</h2>

<p>
    @Html.ActionLink("Voltar", "Index")
</p>
<table class="table">
    <tr>
        <th>
            @Html.Label("Instituição")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nota)
        </th>
        <th>
            @Html.Label("Data")
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Instituicoes.Nome)
        </td> 
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nota)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data)
        </td>
    </tr>
}

</table>

tp_escolas/Views/Pais/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Pais Index</h2>


<div >
    @Html.ActionLink("Editar Informação", "Edit" )
    <br />
    @Html.ActionLink("Pedir Infromaçoes", "LstIns" ) <br />
    @Html.ActionLink("Avaliar", "Avaliacao") <br />
    @Html.ActionLink("Consultar Historico de Avaliações", "HistAvaliacoes" ) <br />
    @Html.ActionLink("Ver actividades das Escolas", "LstActividades") <br /> 
    @Html.ActionLink("Pesquisar", "Pesquisa" ) <br />
 </div>

tp_escolas/Views/Pais/InfoActividades.cshtml
@model IEnumerable<tp_escolas.Models.Actividade>

@{
    ViewBag.Title = "InfoActividades";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>InfoActividades</h2>

<p>
    @Html.ActionLink("Voltar", "LstActividades", new { id = ViewBag.Id})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataInicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataTermino)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataInicio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataTermino)
        </td> 
    </tr>
}

</table>

tp_escolas/Views/Pais/LstActividades.cshtml
@model IEnumerable<tp_escolas.Models.Instituicao>

@{
    ViewBag.Title = "LstActividades";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista De Instituições</h2>

<p>
    @Html.ActionLink("Voltar", "Index")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Morada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodPostal)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Morada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CodPostal)
        </td>
        <td>
            @Html.ActionLink("Ver", "InfoActividades", new { idI=item.InstituicaoID, idP = ViewBag.Id })  
            
        </td>
    </tr>
}

</table>

tp_escolas/Views/Pais/LstIns.cshtml
@model IEnumerable<tp_escolas.Models.Instituicao>

@{
    ViewBag.Title = "LstIns";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Instituições</h2>

<p>
    @Html.ActionLink("Voltar", "Index")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Morada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodPostal)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Morada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CodPostal)
        </td>
        <td>
            @Html.ActionLink("Pedir para aceder", "PedirEntrar", new {idP = ViewBag.IdP, idI=item.InstituicaoID }) 
        </td>
    </tr>
}

</table>

tp_escolas/Views/Pais/Pesquisa.cshtml
@model IEnumerable<tp_escolas.Models.Instituicao>

@{
    ViewBag.Title = "Pesquisa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Pesquisa</h2>
<div>

    <table cellpadding="10">
        <tr>
            <td>Escolha uma Cidade: @Html.DropDownList("Cidade", (SelectList)ViewBag.Cidades, "Todas As cidades", new { id = "Mydrop" })</td>
            <td>
                <div id="Serv" style="max-height:200px;overflow:scroll">
                    <table>
                        @foreach (var it in (SelectList)ViewBag.Servicos)
                        {
                            <tr>
                                <td>
                                    @Html.CheckBox("c", htmlAttributes: new { @value = (string)it.Value } )
                                </td>
                                <td>
                                    @Html.Label((string)it.Text)
                                </td>

                            </tr>
                        }
                    </table>
                </div>
            </td>
            <td>
                <div id="Ensi" style="max-height:200px;overflow:scroll">
                    <table>
                        @foreach (var it in (SelectList)ViewBag.TiposEnsino)
                        {
                            <tr>
                                <td>
                                    @Html.CheckBox("c", htmlAttributes: new { @value = (string)it.Value })
                                </td>
                                <td>
                                    @Html.Label((string)@it.Text)
                                </td>

                            </tr>
                        }
                    </table>
                </div>
            </td>
            <td>
            <td>Escolha um  Tipo de Instituicao: @Html.DropDownList("Tipo Instituicao", (SelectList)ViewBag.Inst, "Todas", new { id = "Inst" })</td>
              
        </tr>
    </table>
</div>
<div id="divPartialView">
    @Html.Partial("_Pesquisa", Model)
</div>
<script>
    $(document).ready(function () {

      
        $("#Serv").contents().find(":checkbox").bind('change', function () {
            pesquisa();
        });
        $("#Ensi").contents().find(":checkbox").bind('change', function () {
            pesquisa();
        });
      
        $("#Mydrop").change(function (event) { 
             pesquisa( );  
        });
        $("#Inst").change(function (event) { 
            pesquisa(); 
        });
         

        function pesquisa() {
            var servicos = [];
            var tensi = []; 

            $('#Serv input:checked').each(function () {
                servicos.push($(this).attr("value"));
            });

            $('#Ensi input:checked').each(function () {
                tensi.push($(this).attr("value"));
            });
  
            var id = $("#Mydrop").val();
            if (id === "")
                id = 0;
            var tesco = $("#Inst").val();
            if (tesco === "")
                tesco = null;

            $.ajax({
                data: JSON.stringify({ id: id, serv: servicos, Tensi: tensi, Tesco: tesco }),
                cache: false,
                method: "POST",
                dataType: 'html', contentType: 'application/json;'
            }).done(function (result) {
                $("#divPartialView").html(result);
            });
        }
             
        
    });
</script>

tp_escolas/Views/Pais/Registo.cshtml
@model tp_escolas.Models.ViewModels.PaiViewModelAdd

@{
    ViewBag.Title = "Registo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pais</h4>
        <hr /> 

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Morada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Morada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Morada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodPostal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodPostal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodPostal, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group">
            @Html.LabelFor(model => model.Cidade, "Cidade", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Cidade.CidadeID, ViewBag.CidadeID as IEnumerable<SelectListItem>)
                 
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registo" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

tp_escolas/Views/Pais/_Pesquisa.cshtml
@model IEnumerable<tp_escolas.Models.Instituicao>
 
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Morada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodPostal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NotaAvg)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Morada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CodPostal)
        </td>
        <td>
            @if (!Double.IsNaN(item.NotaAvg))
            {
                @Html.DisplayFor(modelItem => item.NotaAvg)
            }
            else
            {
                @Html.Label("Ainda não há avaliação")
            }
        </td>
        <td>
            @Html.ActionLink("Mais Info", "Info","Instituicao", new {id=item.InstituicaoID },null) 
        </td>
    </tr>
}

</table>